//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessEntityUsersSettings
    {
        public int AccessEntityId { get; set; }
        public int UserId { get; set; }
        public string ScreenItemTag { get; set; }
        public string SettingXml { get; set; }
    
        public virtual AccessEntity AccessEntity { get; set; }
        public virtual EndUser EndUser { get; set; }
    }
}
