//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccessEntity()
        {
            this.AccessEntityAuthorizations = new HashSet<AccessEntityAuthorizations>();
            this.AccessEntityUsersSettings = new HashSet<AccessEntityUsersSettings>();
            this.Application = new HashSet<Application>();
            this.ApplicationAccess = new HashSet<ApplicationAccess>();
            this.ApplicationAccessActions = new HashSet<ApplicationAccessActions>();
            this.UserEntityPermissionsAccess = new HashSet<UserEntityPermissionsAccess>();
        }
    
        public int AccessEntityId { get; set; }
        public string AccessEntityTypeCd { get; set; }
        public Nullable<System.DateTime> CreationDt { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime LastModDt { get; set; }
        public string LastModBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessEntityAuthorizations> AccessEntityAuthorizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessEntityUsersSettings> AccessEntityUsersSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationAccess> ApplicationAccess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationAccessActions> ApplicationAccessActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEntityPermissionsAccess> UserEntityPermissionsAccess { get; set; }
    }
}
