//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveToken
    {
        public int TokenId { get; set; }
        public int UserId { get; set; }
        public string CompanyCd { get; set; }
        public string ChannelId { get; set; }
        public string IPAddress { get; set; }
        public System.Guid TokenValue { get; set; }
        public Nullable<int> TokenTimeOut { get; set; }
        public System.DateTime CreationDt { get; set; }
        public System.DateTime LastConnAttempt { get; set; }
    
        public virtual EndUser EndUser { get; set; }
    }
}
