//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationAccessActions
    {
        public int ActionId { get; set; }
        public int AccessEntityId { get; set; }
        public int AccessId { get; set; }
        public string ActionTag { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreationDt { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime LastModDt { get; set; }
        public string LastModBy { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual AccessEntity AccessEntity { get; set; }
        public virtual ApplicationAccess ApplicationAccess { get; set; }
    }
}
