//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatSystemCatalogDetail
    {
        public int CatalogId { get; set; }
        public string CatalogKey { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        public virtual CatSystemCatalog CatSystemCatalog { get; set; }
    }
}
