//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatUserSettings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatUserSettings()
        {
            this.UserSettings = new HashSet<UserSettings>();
        }
    
        public int SettingId { get; set; }
        public int SettingTypeId { get; set; }
        public string SettingCd { get; set; }
        public string Name { get; set; }
        public string ValueDefault { get; set; }
        public Nullable<int> MinLength { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public Nullable<int> MinRange { get; set; }
        public Nullable<int> MaxRange { get; set; }
        public Nullable<System.DateTime> CreationDt { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModDt { get; set; }
        public string LastModBy { get; set; }
    
        public virtual CatSettingsDataTypes CatSettingsDataTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSettings> UserSettings { get; set; }
    }
}
