//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EndUser()
        {
            this.AccessEntityUsersSettings = new HashSet<AccessEntityUsersSettings>();
            this.ActiveToken = new HashSet<ActiveToken>();
            this.IPAddress = new HashSet<IPAddress>();
            this.UserProfiles = new HashSet<UserProfiles>();
            this.UserPwdHistoryLog = new HashSet<UserPwdHistoryLog>();
            this.UserSettings = new HashSet<UserSettings>();
        }
    
        public int UserId { get; set; }
        public int DomainId { get; set; }
        public int UserEntityId { get; set; }
        public string CompanyCd { get; set; }
        public string ChannelId { get; set; }
        public string UserTypeCd { get; set; }
        public string UserName { get; set; }
        public byte[] Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string MotherMName { get; set; }
        public string LockedCd { get; set; }
        public Nullable<System.DateTime> LockedDt { get; set; }
        public Nullable<int> Badpwdcount { get; set; }
        public Nullable<System.DateTime> LastLogOnDt { get; set; }
        public Nullable<System.DateTime> CreationDt { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime LastModDt { get; set; }
        public string LastModBy { get; set; }
        public System.DateTime ExpirateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessEntityUsersSettings> AccessEntityUsersSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiveToken> ActiveToken { get; set; }
        public virtual Domain Domain { get; set; }
        public virtual UserEntity UserEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPAddress> IPAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfiles> UserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPwdHistoryLog> UserPwdHistoryLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSettings> UserSettings { get; set; }
    }
}
