//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.UserProfiles = new HashSet<UserProfiles>();
        }
    
        public int ProfileId { get; set; }
        public int DomainId { get; set; }
        public int UserEntityId { get; set; }
        public string ProfileCd { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreationDt { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime LastModDt { get; set; }
        public string LastModBy { get; set; }
    
        public virtual Domain Domain { get; set; }
        public virtual UserEntity UserEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfiles> UserProfiles { get; set; }
    }
}
