//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvSysUserEntityAuthorizations
    {
        public string USER_ENTITY_TYPE_CD { get; set; }
        public Nullable<int> USER_ENTITY_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_LOCKED_CD { get; set; }
        public bool USER_ISENABLED { get; set; }
        public bool USER_ISDELETED { get; set; }
        public string PROFILE_NAME { get; set; }
        public bool PROFILE_ISENABLED { get; set; }
        public bool PROFILE_ISDELETED { get; set; }
        public string ApplicationTag { get; set; }
        public string ApplicationName { get; set; }
        public string AccessTag { get; set; }
        public string AccessName { get; set; }
        public string ActionTag { get; set; }
        public string ActionName { get; set; }
    }
}
